function skillsMember() {
  return [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "Express",
    "Python",
    "Django",
    "AWS",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "SQL",
    "NoSQL",
    "Git",
    "Agile",
    "Scrum",
    "Kanban",
    "JIRA",
    "Slack",
    "Trello",
    "Confluence",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Zeplin",
    "InVision",
    "Photoshop",
    "Illustrator",
    "Premiere",
    "After Effects",
    "Final Cut Pro",
    "Unity",
    "Unreal Engine",
    "Maya",
    "Blender",
    "ZBrush",
    "Substance Painter",
    "Substance Designer",
    "Houdini",
    "Nuke",
    "Mari",
    "Shotgun",
    "Deadline",
    "Renderman",
    "Arnold",
    "V-Ray",
    "Octane",
    "Redshift",
    "Keyshot",
    "Cinema 4D",
    "3ds Max",
    "Rhino",
    "Grasshopper",
    "Revit",
    "AutoCAD",
    "SketchUp",
    "Lumion",
    "Enscape",
    "Twinmotion",
    "Adobe Creative Suite",
    "Microsoft Office",
    "Google Workspace",
    "Zoom",
    "Microsoft Teams",
    "Slack",
    "Trello",
    "Asana",
    "Monday",
    "JIRA",
    "Confluence",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Zeplin",
    "InVision",
    "Photoshop",
    "Illustrator",
    "Premiere",
    "After Effects",
    "Final Cut Pro",
    "Unity",
    "Unreal Engine",
    "Maya",
    "Blender",
    "ZBrush",
    "Substance Painter",
    "Substance Designer",
    "Houdini",
    "Nuke",
    "Mari",
    "Shotgun",
    "Deadline",
    "Renderman",
    "Arnold",
    "V-Ray",
    "Octane",